name: custom_code_analysis
description: custom code analysis rules
version: 1.2.0-dev.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ^1.4.0
  analyzer_plugin: ^0.6.0
  quick_log: ^4.0.1
  path: ^1.8.0
  uuid: ^3.0.1
  glob: ^2.0.1
  source_span: ^1.4.1
  pub_semver: ^2.0.0
  yaml: ^3.1.0
  file: ^6.1.1
  args: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  test: any
