name: custom_code_analysis_bootstrap
version: 0.0.10+2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  custom_code_analysis:
#    path: /Users/chivan/Documents/project/custom_code_analysis
  custom_code_analysis: ^0.0.10+2