name: custom_code_analysis_bootstrap
version: 1.2.3-dev.6

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  custom_code_analysis: 1.2.3-dev.6
#  custom_code_analysis:
#    path: /Users/chivan/Documents/private_project/custom_code_analysis